### PR TITLE
Converter ready for review

### PR DESCRIPTION
**Pull request by RodrigoCoa**
I've finished the converter, I think it's ready for code review. Thanks.

### CODE REVIEW

**Review by AlbertLlanos — APPROVED** [review]
You did a good job rodrigo, now I understand better your code with inheritance practices.

**Comment by Amilcar-B** [comment]
Good job rodrigo, It would only be necessary to add comments so that it can be understood faster what each thing does

**Comment by FreddyClaros** [comment]
Look great to me, good job

**Review by FreddyClaros — APPROVED** [review]
Looks good to me, Good job Rodrigo

**Comment by aquena-code** [comment]
Good Job Rodrigo, I just have this observations

Observations:
  - For some files, they just has to have an empty row at the end
  - For Copyrights, The name of the file in the Copyright, it has to be the same
  - For some files are missing the comment

**Comment by JHAIR** [comment]
Excelent job Rodrigo 
Your class parameters is good congratulations

**Review by JHAIR — APPROVED** [review]
Good Job

**Review by IvanLazo24 — APPROVED** [review]
good code

**Pull request merged**
